apiVersion: v1
entries:
  submariner:
  - apiVersion: v1
    appVersion: 0.6.0
    created: "2021-02-07T04:38:14.874946793Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: b6938196ea102835b6e192c9f9d570ea76927886ace0037e5e998265ead30e45
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v1
    appVersion: 0.6.0
    created: "2021-02-07T04:38:14.873515494Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: f991eeeb0195b50332951aa2504a1a5ca2a45f05ee5ef1342c81b31ae5ff10f2
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v1
    appVersion: 0.4.0
    created: "2021-02-07T04:38:14.872340196Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: e2f11fd1d231b7b1f70274effb471d962bbe7a90383e1213954d3a54af1d4687
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v1
    appVersion: v0.0.4
    created: "2021-02-07T04:38:14.871024297Z"
    description: k8s 1.16.x support
    digest: 6d814e86f82c5e1b7f6c9cd6ed7387b1defd1d56238dfcce654a9b1e2e8042cc
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v1
    appVersion: v0.0.3
    created: "2021-02-07T04:38:14.870217498Z"
    description: k8s 1.16.x support
    digest: 09d528190319d326b65707a2cb87d7f2697e23ac851521f2e156150bc51970db
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v1
    appVersion: v0.0.2
    created: "2021-02-07T04:38:14.869523399Z"
    description: Submariner with custom ipsec ports support
    digest: e7bdee6dd0b8d84a787e83c112efd948426a991a44529a77bfa36edba9606d8d
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v1
    appVersion: v0.0.1
    created: "2021-02-07T04:38:14.868806899Z"
    description: Submariner
    digest: 3519f07bb8caa3b3dab5137e3fc7dec4862eb0f306d196d882c0f416033d89df
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.1.tgz
    version: 0.0.1
  submariner-k8s-broker:
  - apiVersion: v1
    appVersion: 0.6.0
    created: "2021-02-07T04:38:14.876934091Z"
    description: Submariner Kubernetes Broker
    digest: 7e64c78deba780ba993988129efa04cd5ae91d88e69907dc305d815f6d9aff04
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v1
    appVersion: 0.6.0
    created: "2021-02-07T04:38:14.876432791Z"
    description: Submariner Kubernetes Broker
    digest: 5cfa35b47e3b102e064dd4daec15d9f97ddf3cd6c8f1c1ed4dc782016de16a31
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v1
    appVersion: 0.4.1
    created: "2021-02-07T04:38:14.876065792Z"
    description: Submariner Kubernetes Broker
    digest: a3b99b87d9bd31b20c8faa35e43ea9df4dc369e8ccb05ac6edae93d2242cf8ba
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v1
    appVersion: v0.0.2
    created: "2021-02-07T04:38:14.875696892Z"
    description: Submariner Kubernetes Broker
    digest: efc0faba08ed579c6729d02e8d2a5d9826f3bec4119258ae806b30b7625c4150
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v1
    appVersion: v0.0.1
    created: "2021-02-07T04:38:14.875293093Z"
    description: Submariner Kubernetes Broker
    digest: a5961dd730ee2c593e86a45c566ce62846fdb1a60b235be4561246d80ec0051e
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.0.1.tgz
    version: 0.0.1
  submariner-operator:
  - apiVersion: v1
    appVersion: 0.7.0
    created: "2021-02-07T04:38:14.87772109Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 6d2562e1e2b1d0deda5f6190e895e622f8d918488e65ed4014530d25b86323d8
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.7.0.tgz
    version: 0.7.0
generated: "2021-02-07T04:38:14.868055Z"
